INSERT INTO public.address (id, city, state, street, zip) VALUES (1, 'New York', 'NY', 'Wall Street', '10005');
INSERT INTO public.address (id, city, state, street, zip) VALUES (2, 'Los Angeles', 'CA', 'Sunset Blvd', '90026');
INSERT INTO public.address (id, city, state, street, zip) VALUES (3, 'Chicago', 'IL', 'Wacker Dr', '60606');
INSERT INTO public.address (id, city, state, street, zip) VALUES (4, 'Houston', 'TX', 'Westheimer Rd', '77042');
INSERT INTO public.address (id, city, state, street, zip) VALUES (5, 'Phoenix', 'AZ', 'Camelback Rd', '85016');
INSERT INTO public.address (id, city, state, street, zip) VALUES (6, 'Philadelphia', 'PA', 'Market Street', '19103');
INSERT INTO public.address (id, city, state, street, zip) VALUES (7, 'San Antonio', 'TX', 'Broadway St', '78209');
INSERT INTO public.address (id, city, state, street, zip) VALUES (8, 'San Diego', 'CA', 'Fifth Ave', '92101');
INSERT INTO public.address (id, city, state, street, zip) VALUES (9, 'Dallas', 'TX', 'Main St', '75202');
INSERT INTO public.address (id, city, state, street, zip) VALUES (10, 'San Jose', 'CA', 'Santa Clara St', '95113');
