INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (9, 'Synthetic motor oil for high-performance engines', 'Car Oil', 3.5, 22.9, 4988, 10.5, 3, 9, 9);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (7, 'Pure and natural honey', 'Organic Honey', 3, 15.99, 21, 9, 3, 7, 9);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (8, 'Anti-aging facial cream', 'Facial Cream', 3.5, 45.59, 1988, 10.5, 3, 8, 9);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (3, 'Compact microwave oven with grill function', 'Microwave', 3.625, 150, 83, 14.5, 4, 3, 5);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (2, 'Waterproof winter jacket', 'Jacket', 2.8333333, 99.99, 1982, 17, 6, 2, 5);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (1, 'High-performance laptop suitable for gaming and professional work', 'Laptop', 3.857143, 1200, 139, 27, 7, 1, 5);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (6, 'Family board game for all ages', 'Board Game', 2, 34.95, 384, 6, 3, 6, 7);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (5, 'Lightweight racket for advanced players', 'Tennis Racket', 3.8333333, 210.99, 36, 11.5, 3, 5, 7);
INSERT INTO public.product (id, description, name, over_all_rating, price, quantity, rating_sum, total_user, category_id, seller_id) VALUES (4, 'Latest bestseller in fiction', 'Novel', 4.5, 19.95, 270, 13.5, 3, 4, 7);
