INSERT INTO public.review (id, content, rating, product_id) VALUES (1, 'Excellent laptop with great performance', 5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (2, 'Good for gaming but a bit heavy', 4.5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (3, 'Battery life could be better', 3.5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (4, 'Perfect for professional use.', 5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (5, 'Too expensive for the specs offered', 1.5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (6, 'Amazing screen resolution and speed', 5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (7, 'Heats up quite a bit under load', 2.5, 1);
INSERT INTO public.review (id, content, rating, product_id) VALUES (8, 'Great fit and kept me warm in winter.', 5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (9, 'Zippers feel cheap', 1.5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (10, 'Stylish and functional, but a bit stiff initially.', 3.5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (11, 'Sleeves are a bit too long', 0.5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (12, 'Not as durable as expected.', 1.5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (13, 'High quality material', 5, 2);
INSERT INTO public.review (id, content, rating, product_id) VALUES (14, 'Heats evenly and quickly, very satisfied.', 5, 3);
INSERT INTO public.review (id, content, rating, product_id) VALUES (15, 'Easy to clean and maintain.', 4, 3);
INSERT INTO public.review (id, content, rating, product_id) VALUES (16, 'Controls are not very intuitive.', 1.5, 3);
INSERT INTO public.review (id, content, rating, product_id) VALUES (17, 'Captivating story, couldn''t put it down.', 5, 4);
INSERT INTO public.review (id, content, rating, product_id) VALUES (18, 'Loved the detailed world-building.', 5, 4);
INSERT INTO public.review (id, content, rating, product_id) VALUES (19, 'Great control and feel during games.', 5, 5);
INSERT INTO public.review (id, content, rating, product_id) VALUES (20, 'String tension was not as expected', 2.5, 5);
INSERT INTO public.review (id, content, rating, product_id) VALUES (21, 'Some pieces were missing in the box.', 0.5, 6);
INSERT INTO public.review (id, content, rating, product_id) VALUES (22, 'Packaging could be better, leaked during shipping.', 0, 7);
INSERT INTO public.review (id, content, rating, product_id) VALUES (23, 'Feels great on the skin, very hydrating.', 4.5, 8);
INSERT INTO public.review (id, content, rating, product_id) VALUES (24, 'Works well in different weather conditions', 3.5, 9);
INSERT INTO public.review (id, content, rating, product_id) VALUES (25, 'Improved engine performance noticeably.', 5, 9);
INSERT INTO public.review (id, content, rating, product_id) VALUES (26, 'Does not last as long as other brands', 2, 9);
INSERT INTO public.review (id, content, rating, product_id) VALUES (27, 'Caused a mild rash, might not suit sensitive skin.', 1.5, 8);
INSERT INTO public.review (id, content, rating, product_id) VALUES (28, 'Nice packaging and pleasant scent.', 4.5, 8);
INSERT INTO public.review (id, content, rating, product_id) VALUES (29, 'Would prefer larger size options.', 4.5, 7);
INSERT INTO public.review (id, content, rating, product_id) VALUES (30, 'Delicious and pure, tastes great', 4.5, 7);
INSERT INTO public.review (id, content, rating, product_id) VALUES (31, 'Educational and entertaining.', 5, 6);
INSERT INTO public.review (id, content, rating, product_id) VALUES (32, 'Instructions were complicated to follow', 0.5, 6);
INSERT INTO public.review (id, content, rating, product_id) VALUES (33, 'A bit pricey but worth the investment.', 4, 5);
INSERT INTO public.review (id, content, rating, product_id) VALUES (34, 'Well-written but predictable plot.', 3.5, 4);
INSERT INTO public.review (id, content, rating, product_id) VALUES (35, 'Easy to clean and maintain.', 4, 3);
